version: '3.8'
services:
  db:
    image: postgres:13.3-alpine
    ports:
      - '15430:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'public'
